// Thông tin hệ thống rạp
export const CINEMA_SYSTEM_INFORMATION_REQUEST =
  "@cinema/CINEMA_SYSTEM_INFORMATION_REQUEST";

export const CINEMA_SYSTEM_INFORMATION_SUCCESS =
  "@cinema/CINEMA_SYSTEM_INFORMATION_SUCCESS";

export const CINEMA_SYSTEM_INFORMATION_FAILED =
  "@cinema/CINEMA_SYSTEM_INFORMATION_FAILED";

// Thông tin cụm rạp
export const SET_CINEMA_CLUSTER_INFORMATION =
  "@cinema/SET_CINEMA_CLUSTER_INFORMATION";

// Lịch chiếu phim
export const INFO_FILM_SHOWTIMES_REQUEST =
  "@cinema/INFO_FILM_SHOWTIMES_REQUEST";

export const INFO_FILM_SHOWTIMES_SUCCESS =
  "@cinema/INFO_FILM_SHOWTIMES_SUCCESS";

export const INFO_FILM_SHOWTIMES_FAILED =
  "@cinema/INFO_FILM_SHOWTIMES_FAILED";

// Lịch chiếu hệ thống rạp

export const SET_INFO_SHOWTIMES_CINEMA_SYSTEM =
  "@cinema/SET_INFO_SHOWTIMES_CINEMA_SYSTEM";
