// Thông tin hệ thống rạp
export const CINEMA_SYSTEM_INFORMATION_REQUEST =
  "@cinema/CINEMA_SYSTEM_INFORMATION_REQUEST";

export const CINEMA_SYSTEM_INFORMATION_SUCCESS =
  "@cinema/CINEMA_SYSTEM_INFORMATION_SUCCESS";

export const CINEMA_SYSTEM_INFORMATION_FAILED =
  "@cinema/CINEMA_SYSTEM_INFORMATION_FAILED";

// Thông tin cụm rạp
export const SET_CINEMA_CLUSTER_INFORMATION =
  "@cinema/SET_CINEMA_CLUSTER_INFORMATION";
