export const TICKET_ROOM_REQUEST = "@ticket/TICKET_ROOM_REQUEST";
export const TICKET_ROOM_SUCCESS = "@ticket/TICKET_ROOM_SUCCESS";
export const TICKET_ROOM_FAILED = "@ticket/TICKET_ROOM_FAILED";
export const ADD_SEAT_SELECTED = "@ticket/ADD_SEAT_SELECTED";
export const RESET_SEAT_SELECTED = "@ticket/RESET_SEAT_SELECTED";
